### ISSUE TITLE
CAJ 转换错误

### ISSUE THREAD

**Issue by Cpy-bit** [caj2pdf/caj2pdf#59]
Could not find module 'libjbigdec-w64.dll'

**Comment by liudonghua123** [comment]
I have the same problems.

When I tried with `python caj2pdf convert test.caj -o test.pdf`, I got the following errors.
```shell
Traceback (most recent call last):
  File "caj2pdf", line 52, in <module>
    caj.convert(args.output)
  File "D:\code\other\caj2pdf\cajparser.py", line 109, in convert
    self._convert_hn(dest)
  File "D:\code\other\caj2pdf\cajparser.py", line 337, in _convert_hn
    from jbigdec import CImage
  File "D:\code\other\caj2pdf\jbigdec.py", line 25, in <module>
    libjbigdec = cdll.LoadLibrary("libjbigdec-w64.dll")
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.2544.0_x64__qbz5n2kfra8p0\lib\ctypes\__init__.py", line 451, in LoadLibrary
    return self._dlltype(name)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.2544.0_x64__qbz5n2kfra8p0\lib\ctypes\__init__.py", line 373, in __init__
    self._handle = _dlopen(self._name, mode)
FileNotFoundError: Could not find module 'libjbigdec-w64.dll' (or one of its dependencies). Try using the full path with constructor syntax.
```

But I can confirm that I have 'libjbigdec-w64.dll' side the `caj2pdf`.

**Comment by JeziL** [comment]
seems just a path issue on Windows ... prefixing `./` to the path fixed the issue. ( c041bff )
pull the latest commit and it should work now

**Comment by ClementLevi** [comment]
This problem is still unresolved with newest commit. CAJ file has to be dragged into the same path with the project, and it goes normal. There should be some problem with the module locating and importing, as I have even configured the project entry file and the path into system variables.
拖到项目根目录才能用，最新commit也无效。估计是dll导入或者寻址有问题，项目入口文件和项目地址我都加环境变量了

**Comment by HinTak** [comment]
You probably use caj2pdf in a different way from us (we always run caj2pdf from the source code folder). I think for your problem, the easiest solution is simply to copy 'libjbigdec-w64.dll' from our source, into your computer's system folder ie. "c:\windows\system32" . That should fix your kind of problem.

**Comment by HinTak** [comment]
FWIW, I am not convinced aboout the "./lib/bin/..." construct. Library loading is simply different between Linux and Windows. Without "./", Linux only looks at system locations (everywhere on LD_LIBRARY_PATH, I think), but Windows would look everywhere in PATH (and current directory in included by default on windows). With "./", both restrict to looking at relative locations only, I think. Thus "./..." is more restrictive, but works in our normal usage, which is running ./caj2pdf inside the project folder.

I think the correct solution is different for linux and windows. For Linux, we want "./", as system location is often not writable. But for windows, we do not want "./", since that is included by default anyway, but teaches users who want to run caj2pdf from a different location (often not up to them, but subjected to python installation, etc) as the project folder, to copy those dll's into system locations or into where $PATH points to.

There is no one quick solution to everybody.
